version: '3'

volumes:
  vocup_local_postgres_data: {}
  vocup_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sompodbd/vocupdev:vocup_local_django
    container_name: vocup_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "80:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sompodbd/vocupdev:vocup_production_postgres
    container_name: vocup_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - vocup_local_postgres_data:/var/lib/postgresql/data:Z
      - vocup_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: vocup_local_redis
