version: '3'

volumes:
  vocup_local_postgres_data: {}
  vocup_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sompodbd/vocupdev:vocup_local_django
    container_name: vocup_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sompodbd/vocupdev:vocup_production_postgres
    environment:
      POSTGRE_USER: debug
      POSTGRE_PASSWORD: debug
      POSTGRE_DB: vocup
      POSTGRE_HOST: postgres
      POSTGRE_PORT: 5432

    container_name: vocup_local_postgres
    volumes:
      - vocup_local_postgres_data:/var/lib/postgresql/data:Z
      - vocup_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
